### ISSUE TITLE
NotImplementedError: The matplotlib backend agg is not yet supported.

### ISSUE THREAD

**Issue by jennmald** [NSLS-II/sirepo-bluesky#10]
I have been following the tutorial for Sirepo-Bluesky and reach an error when trying to prepare Bluesky and trigger a simulated Sirepo detector. For the line,
`%run -i examples/prepare_det_env.py`
I received the error,
`NotImplementedError: The matplotlib backend agg is not yet supported.`
While looking into this I found this issue:
https://github.com/bluesky/bluesky/issues/1087
Looking at the solution, I commented out `install_kicker()` in the `prepare_det_env.py` file which allowed the rest of the tutorial to run without matplotlib issues.

A more detailed version of the error is shown below:
```
In [1]: %run -i examples/prepare_det_env.py
/home/vagrant/miniconda3/envs/sirepo_bluesky/lib/python3.7/site-packages/pims/image_reader.py:26: RuntimeWarning: PIMS image_reader.py could not find scikit-image. Falling back to matplotlib's imread(), which uses floats instead of integers. This may break your scripts. 
(To ignore this warning, include the line "warnings.simplefilter("ignore", RuntimeWarning)" in your script.)
  warnings.warn(RuntimeWarning(ski_preferred))
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
~/sirepo-bluesky/examples/prepare_det_env.py in <module>
     30 
     31 plt.ion()
---> 32 install_kicker()
     33 
     34 root_dir = '/tmp/sirepo_flyer_data'

~/miniconda3/envs/sirepo_bluesky/lib/python3.7/site-packages/bluesky/utils.py in install_kicker(loop, update_rate)
    895     else:
    896         raise NotImplementedError("The matplotlib backend {} is not yet "
--> 897                                   "supported.".format(backend))
    898 
    899 

NotImplementedError: The matplotlib backend agg is not yet supported.
```

**Comment by mrakitin** [comment]
Thanks for the report, @jennmald. A solution to that would be to create the following file:
```bash
$ cat ~/.matplotlib/matplotlibrc
backend : Qt5Agg
```

That will enable the `Qt5Agg` backend for Matplotlib.

With your solution, were you able to get the live plots? They are pretty useful for grid scans.

**Comment by jennmald** [comment]
This helped a lot! @jklynch and I realized I also needed xquartz (https://www.xquartz.org) installed. With the original idea I had the live plots did not come up so this fixed that. We are having some databroker version issues that we will be working on soon. Thanks again @mrakitin !!

**Comment by mrakitin** [comment]
My pleasure, @jennmald! Thanks for tinkering with that package.

**Comment by mrakitin** [comment]
Regarding `xquartz`, that is only needed for macOS and only in the case when you are trying to visualize things from a remote machine you are ssh-ing in. If you run everything on a laptop (besides Sirepo), that should work fine without it.

What is your setup?

It should work out of the box on any X11-enabled Linux system.

**Comment by jennmald** [comment]
We are using a virtual machine using Vagrant and VirtualBox on my Mac. We have not tried any other setup so the `xquartz` allows us to do exactly what you mentioned with visualization. 
We haven't tried the X11-enabled linux setup which might be useful too!

**Comment by mrakitin** [comment]
> We are using a virtual machine using Vagrant and VirtualBox on my Mac. We have not tried any other setup so the `xquartz` allows us to do exactly what you mentioned with visualization.
> We haven't tried the X11-enabled linux setup which might be useful too!

I see, so you are ssh-ing to the VM and run the bluesky plans from there? In principle, you can run it directly from Mac, which will not require the xquartz to be installed, but it's good to have it installed.
 
> @jklynch suggested I also mention this warning:
> 
> ```
> /home/vagrant/miniconda3/envs/sirepo_bluesky/lib/python3.7/site-packages/bluesky/utils.py:914: UserWarning: bluesky.utils.install_qt_kicker is no longer necessary and has no effect. Please remove your use of it. It may be removed in a future release of bluesky.
>   warnings.warn("bluesky.utils.install_qt_kicker is no longer necessary
> ```

Feel free to submit a PR with the update. Indeed, for the latest bluesky versions 1.6+ it's not needed.

**Comment by jennmald** [comment]
Okay! Will do, thank you!
