### ISSUE TITLE
Changing grazing angle does not recompute pointing vectors correctly

### ISSUE THREAD

**Issue by thomaswmorris** [NSLS-II/sirepo-bluesky#72]
<img width="481" alt="Screen Shot 2022-03-09 at 11 44 33 AM" src="https://user-images.githubusercontent.com/41275226/157507317-e23b8092-41d7-40b4-a1c9-98b932c20253.png">

"tvy" should be sin(grazingAngle) ~= grazingAngle = 10/1000 = 0.01

**Comment by mrakitin** [comment]
Good point, @thomaswmorris!

@moellep, looks like there is a bug in Sirepo. When I try to manually change the grazing angle, it does not update the corresponding vector components. Below are a few examples:

## TES toroidal mirror - grazing angle=7 mrad:
![image](https://user-images.githubusercontent.com/13209176/157684693-c6772bc6-f1fc-4904-bcb3-df050729636c.png)

## TES toroidal mirror - grazing angle=10 mrad:
![image](https://user-images.githubusercontent.com/13209176/157684777-880c5e42-b853-40a3-9f0f-0df855e9da31.png)

I tried it in both Firefox and Chrome, and the result is the same. Also, tried to check the network traffic in the web-developer's Network tab, and saw no headers passed to the server. Should we open an issue in radiasoft/sirepo? Thanks!

**Comment by moellep** [comment]
Yes, this could be a bug. Could you share the URL for the simulation which is causing the problem? When I tried it just now with chrome on sirepo.com, it looks OK. It should make a "stateless-compute" request any time something is typed into the grazing angle field.
![Screen Shot 2022-03-10 at 9 57 25 AM](https://user-images.githubusercontent.com/6516910/157715235-0b46f654-c3e5-4ef5-a09d-6837bfcb2ec2.png)

**Comment by mrakitin** [comment]
Weird, it seems to be working now. Probably was something to do with my browser's state, network connection and/or VPN. Thanks for checking and sorry for the noise, @moellep!

@thomaswmorris, I am working on the fix for the test. It indeed has wrong expected values.

**Comment by moellep** [comment]
Good to hear - if it does happen again, please let me know the simulation URL and I can check the server logs.
