### ISSUE TITLE
Suggestion in SirepoWatchpoint.trigger

### ISSUE THREAD

**Issue by magiconline** [NSLS-II/sirepo-bluesky#78]
I want to get the image of an watchpoint object in my plan. So I first tried something like `w8.image.get()` it returns a random uuid. 

After reading your code, I find SirepoWatchpoint.trigger use different uuid in saving the image into a file and `self.iamge.put()`.  

It seems `w8.image.get()` is meaningless so I suggest `w8.image.get()` should return the image file path or image data like this:

![image](https://user-images.githubusercontent.com/31735317/169642818-08655a38-1864-4298-a0d9-2812b8d291f2.png)

**Comment by mrakitin** [comment]
@magiconline, thanks for contacting us and your ongoing interest in our library.

In this library, we follow the ophyd abstraction as close as possible to the abstraction of the hardware detectors/devices, backed by EPICS at NSLS-II and other facilities. The `image` component is an [`ExternalFileReference`](https://github.com/NSLS-II/sirepo-bluesky/blob/05be2df43d56f2b5e69fb9511de9a424ad1e8b79/sirepo_bluesky/sirepo_ophyd.py#L67), meaning that the reference to the data file (not the file contents) is expected to be there. That information is then propagated to the resource/datum documents, which are used to point to the file in your file system and to fill the data with the specified handler. Please read the corresponding documentation at https://blueskyproject.io/event-model/external.html.

To access the specific files, please use the databroker API, as outlined in our [documentation](http://nsls-ii.github.io/sirepo-bluesky/notebooks/elements.html#Run-%E2%80%9CBeamline%E2%80%9D-SRW-simulations):
```py
(uid,) = RE(bp.scan([w9], aperture.horizontalSize, 0, 2, 5))

hdr = db[uid]
w9_image = np.array(list(hdr.data("w9_image")))
```

The databroker instance `db` is defined in https://github.com/NSLS-II/sirepo-bluesky/blob/05be2df43d56f2b5e69fb9511de9a424ad1e8b79/examples/prepare_det_env.py#L21-L26
and that's the place where the handlers for reading the raw data files are registered.

**Comment by mrakitin** [comment]
Please let us know if it answers your questions. If so, I propose closing this issue.

**Comment by magiconline** [comment]
I understand why it designed like this. Thanks.
